# Generated by Django 2.2.2 on 2020-03-23 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='question',
        ),
    ]
